stages:
  - build
  - run
  - lint
  - cleanup
  - deploy

build-job:
  stage: build
  environment:
    name: dev
  script:
    - docker compose -f docker-compose.yml build

run-job:
  stage: run
  environment:
    name: dev
  needs: [build-job]
  script:
    - docker compose -f docker-compose.yml up -d

lint-test-job:
  stage: lint
  environment:
    name: dev
  needs: [run-job]
  script:
    - echo "Проверка форматирования кода с помощью ruff..."
    - docker compose exec -it candy_store_tg_bot ruff format --config ruff.toml --check bot

    - echo "Проверка типов с помощью pyright..."
    - docker compose exec -it candy_store_tg_bot pyright bot

    - echo "Проверка стиля кода с помощью ruff..."
    - docker compose exec -it candy_store_tg_bot ruff check --config ruff.toml bot

    - echo "Проверка сортировки импортов с помощью isort..."
    - docker compose exec -it candy_store_tg_bot isort --check-only --diff bot


cleanup-job:
  stage: cleanup
  environment:
    name: dev
  needs: [run-job, lint-test-job]
  script:
    - docker compose -f docker-compose.yml down
    - docker container prune -f
    - docker volume prune -f
    - docker system prune -f
  when: always


deploy-job:
  stage: deploy
  environment:
    name: dev
  needs: [test-job]
  script:
    - docker compose -f docker-compose.yml build
    - docker compose -f docker-compose.yml up -d
  when: manual
