services:
  candy_store_tg_bot:
    image: candy_store_tg_bot_image:latest
    build:
      context: .
    container_name: candy_store_tg_bot_container
    env_file:
      - .env-non-dev
    restart: always
    networks:
      - rabbitmq_network

  faststream:
    build:
      context: .
    env_file:
      - .env-non-dev
    entrypoint:
      [ "bash", "/candy_store_tg_bot/docker/faststream.sh" ]
    networks:
      - rabbitmq_network

networks:
  rabbitmq_network:
    external: true  # Используем существующую сеть